services:
  db:
    image: mariadb:latest
    container_name: mts-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: URafyiip9Q*Ws
      MYSQL_DATABASE: data
      MYSQL_USER: o8uc2o6OLVPOD
      MYSQL_PASSWORD: URafyiip9Q*Ws
    ports:
      - "3306:3306"
    volumes:
      - ./data/db_data:/var/lib/mysql
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      internal:
        ipv4_address: 172.28.0.10

  backend:
    image: php:8.2-apache
    container_name: mts-backend
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html
      - ./config/vhost.conf:/etc/apache2/sites-available/000-default.conf
    restart: always
    depends_on:
      - db
    command: >
       bash -c "apt-get update &&
             apt-get install -y libpng-dev libjpeg-dev libonig-dev libxml2-dev zip unzip &&
             docker-php-ext-install mysqli &&
             a2enmod rewrite &&
             apache2-foreground"
    networks:
      internal:
        ipv4_address: 172.28.0.11


  mc-gate:
    image: ghcr.io/minekube/gate:latest
    container_name: mts-mc-gate
    ports:
      - "25565:25565"
    restart: unless-stopped
    volumes:
      - ./config/config.yml:/config.yml
    networks:
      internal:
        ipv4_address: 172.28.0.12
        
  server:
    build: ./server
    container_name: mts-mc-server
    volumes:
      - ./data/servers:/mc/servers
    tty: true
    stdin_open: true

#  frontend-dev:
#    image: node:23
#    working_dir: /frontend
#    volumes:
#      - ./frontend:/frontend
#    ports:
#      - "5173:5173"
#    command: sh -c "npm install && npm run dev -- --host"

volumes:
  db_data:

networks:
  internal:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16